// CppIDE.idl: CppIDE.exe 的类型库源

// 此文件将由 MIDL 编译器处理以产生
// 类型库(CppIDE.tlb)。

[ uuid(77328bc0-75a5-4eac-b85f-7ecd66bde32c), version(1.0) ]
library CppIDE
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	//  CCppIDEDoc 的主调度接口

	[ uuid(2ea2570e-1cf5-4149-8e89-ea815655069d) ]
	dispinterface ICppIDE
	{
		properties:

		methods:
	};

	//  CCppIDEDoc 的类信息

	[ uuid(ac1c77d6-f1fe-41fd-8f5d-32a594151d20) ]
	coclass CCppIDEDoc
	{
		[default] dispinterface ICppIDE;
	};
};
